
services:
  nginx:
    build: requeriments/nginx/.
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "80:80"
    volumes:
      - wp:/var/www/html
    networks:
      inception:
  wordpress:
    build: requeriments/wordpress/.
    container_name: wp-php
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      inception:
  mariadb:
    build: requeriments/mariadb/.
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      inception:

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      device: /home/pedromar/data/wordpress
      o: bind
      type: none
  db:
    name: db
    driver: local
    driver_opts:
      device: /home/pedromar/data/mariadb
      o: bind
      type: none
networks:
  inception: