#
# NETWORKS
#
networks:
  inception:
    name: inception

#
# VOLUMES
#
volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      device: /home/pedromar/data/wordpress
      o: bind
      type: none
  db:
    name: db
    driver: local
    driver_opts:
      device: /home/pedromar/data/mariadb
      o: bind
      type: none

#
# SERVICES
#
services:
  nginx:
    build: requeriments/nginx/.
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      inception:
    ports:
      - "443:443"
    expose:
      - "443"
    depends_on:
      - wordpress
      - mariadb
    restart: on-failure
  wordpress:
    build: requeriments/wordpress/.
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      inception:
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: on-failure
  mariadb:
    build: requeriments/mariadb/.
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      inception:
    expose:
      - "3306"
    restart: on-failure
